<?php
$page_start = microtime(TRUE);

function curPageName() {
	return 'install/'.substr($_SERVER["SCRIPT_NAME"],strrpos($_SERVER["SCRIPT_NAME"],"/")+1);
}

function getURL() {
	$pageURL = 'http';
	if(isset($_SERVER["HTTPS"]))
	{
		if ($_SERVER["HTTPS"] == "on") {$pageURL .= "s";}
	}
	$pageURL .= "://";
	if ($_SERVER["SERVER_PORT"] != "80") {
		$pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];
	} else {
		$pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
	}
	$pageURL = str_replace(curPageName(), '', $pageURL);
	//$pageURL = str_replace(, '', $pageURL);
	return $pageURL;
}

include '../Page.php';

$page=new Page('../install');

if(isset($_POST['action']) && $_POST['action']=='install_gradebook')
{
	$tags=array('hostname'=>$_POST['hostname'], 'username'=>$_POST['username'], 'password'=>$_POST['password'], 'db_name'=>$_POST['db_name'], 'url'=>getURL());
	$config='<?php
/*This file is automatically generated by the Gradebook install process, and should not be tampered with under any circumstances*/
$hostname="[hostname]";
$username="[username]";
$password="[password]";
$db_name="[db_name]";

function getURL() { return "[url]"; }
?>';
	$page->page=$page->load_page('install2');
	$page->replace_tags($tags, $config);
	echo "<textarea rows=\"10\" cols=\"50\">$config</textarea>";
} else {
	$page->page=$page->load_page('install');
}

$page->output_page();
?>